fragment ContentParts on Content {
  __typename
  SITE_CONFIG {
    __typename
    name
    tagline
    description
    company
  }
  NAVIGATION_ITEMS {
    __typename
    label
    href
  }
  HERO_CONTENT {
    __typename
    headline
    headlineAccent
    subheadline
    videoUrl
    ctaPrimary {
      __typename
      label
      href
    }
    ctaSecondary {
      __typename
      label
      href
    }
  }
  TRUST_STATS {
    __typename
    value
    label
    sublabel
  }
  PROBLEM_CONTENT {
    __typename
    statistic
    statisticLabel
    headline
    subheadline
    source
  }
  SOLUTION_CONTENT {
    __typename
    headline
    features
    description
  }
  NINE_MOVEMENTS {
    __typename
    id
    name
    description
  }
  COMPARISON_TABLE {
    __typename
    headline
    subheadline
    features {
      __typename
      label
      description
    }
  }
  TESTIMONIALS {
    __typename
    quote
    author
    role
  }
  PROCESS_PHASES {
    __typename
    number
    title
    subtitle
    description
    details
    duration
  }
  PRICING_PACKAGES {
    __typename
    name
    posts
    idealFor
    price
    highlighted
    badge
    features {
      __typename
      name
      included
    }
  }
  IMPULSWORKSHOP {
    __typename
    headline
    subheadline
    description
    price
    priceNote
    duration
    participants
    location
    weather
    targetAudience
    program {
      __typename
      title
      description
    }
    outcomes
  }
  FAQ_ITEMS {
    __typename
    question
    answer
  }
  CTA_CONTENT {
    __typename
    headline
    subheadline
    ctaPrimary {
      __typename
      label
      href
    }
    ctaSecondary {
      __typename
      label
      href
    }
    downloads {
      __typename
      label
      href
    }
  }
  CONTACT_PERSON {
    __typename
    name
    role
    email
    phone
  }
  CONTACT_INFO {
    __typename
    company
    street
    city
    email
    phone
  }
  FOOTER_LINKS {
    __typename
    hauptseiten {
      __typename
      label
      href
    }
    rechtliches {
      __typename
      label
      href
    }
    partner {
      __typename
      label
      href
      logo
    }
  }
  KOENIZ_CASE_STUDY {
    __typename
    headline
    subheadline
    intro
    challenge {
      __typename
      title
      points
    }
    solution {
      __typename
      title
      points
    }
    insights {
      __typename
      title
      shortDesc
      fullDesc
    }
    timeline {
      __typename
      date
      event
    }
    denkmalpflege
    workshopFeedback
  }
  PARTNERS {
    __typename
    name
    description
    url
  }
  STAKEHOLDER_BENEFITS {
    __typename
    gemeinden {
      __typename
      title
      benefits
    }
    bildung {
      __typename
      title
      benefits
    }
    bevoelkerung {
      __typename
      title
      benefits
    }
  }
  SAFETY_INFO {
    __typename
    headline
    description
    norms {
      __typename
      code
      name
    }
  }
  FLEXIBILITY_INFO {
    __typename
    headline
    description
    services {
      __typename
      name
      description
      optional
    }
  }
  PARKOURONE_STORY {
    __typename
    headline
    description
    milestones {
      __typename
      year
      title
      description
    }
  }
  WORKSHOP_DETAILS {
    __typename
    duration
    participants
    targetGroups {
      __typename
      name
      description
    }
    faq {
      __typename
      question
      answer
    }
  }
  CONFIGURATOR {
    __typename
    packages {
      __typename
      name
      posts
      basePrice
      description
      highlighted
    }
    additionalServices {
      __typename
      name
      price
      description
    }
  }
  IMAGE_CONCEPTS {
    __typename
    hero
    problem
    solution
    koeniz
    workshop
    team
  }
}
